name: Deploy to Vercel

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel@54.14.0 --prod --token="$VERCEL_TOKEN"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: team_kZGK8yx5oGBj2ZTWAdhhi2FU
          VERCEL_PROJECT_ID: prj_VqJ7Jdcbc4AUsXi3CdWHn3HIz0uz
