name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_kZGK8yx5oGBj2ZTWAdhhi2FU
          VERCEL_PROJECT_ID: prj_VqJ7Jdcbc4AUsXi3CdWHn3HIz0uz
